// 1444 开局国家、颜色、首都、宗教、文化、权重、省份命名表
// 权重用于地图生成时的「势力范围」大小，不严格等于历史疆域，只保证大国够大、小国存在。

export function hexToRgb(hex) {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}

const C = (hex) => hexToRgb(hex);

export const RELIGIONS = {
  catholic: { name: '天主教', en: 'Catholic' },
  orthodox: { name: '东正教', en: 'Orthodox' },
  sunni: { name: '逊尼派', en: 'Sunni' },
  hussite: { name: '胡斯派', en: 'Hussite' },
  shia: { name: '什叶派', en: 'Shia' },
  coptic: { name: '科普特正教', en: 'Coptic' },
};

export const CULTURES = {
  french: '法兰西', english: '英格兰', iberian: '伊比利亚', german: '德意志',
  italian: '意大利', scandinavian: '斯堪的纳维亚', slavic: '斯拉夫', russian: '罗斯',
  polish: '波兰', lithuanian: '立陶宛', hungarian: '马扎尔', romanian: '罗马尼亚',
  turkish: '突厥', persian: '波斯', arabic: '阿拉伯', berber: '柏柏尔',
  greek: '希腊', serbian: '塞尔维亚', croatian: '克罗地亚', czech: '捷克',
  irish: '爱尔兰', scottish: '苏格兰', georgian: '格鲁吉亚', azeri: '阿塞拜疆',
  baltic: '波罗的', finnish: '芬兰', latin: '拉丁', basque: '巴斯克',
};

export const TECH_GROUPS = {
  western: '西欧', eastern: '东欧', ottoman: '奥斯曼', muslim: '穆斯林', nomad: '游牧',
};

export const GOVS = {
  monarchy: '君主制', theocracy: '神权制', republic: '共和制', horde: '游牧汗国',
};

export const COUNTRIES = [
  /* ─── 西欧 ─── */
  { tag: 'FRA', name: '法兰西', en: 'France', adj: '法兰西', color: C('#3862a8'),
    capital: ['巴黎', 2.35, 48.85], religion: 'catholic', culture: 'french', tech: 'western', gov: 'monarchy', weight: 26, hre: false,
    names: ['法兰西岛','博韦','桑利斯','诺曼底','香槟','皮卡第','奥尔良','图赖讷','曼恩','安茹','普瓦图','贝里','布尔日','利穆赞','奥弗涅','吉耶讷','加斯科涅','图卢兹','朗格多克','多菲内','鲁西永','康布雷','拉马什','桑通日','欧尼斯','马尔什','讷韦尔'] },
  { tag: 'ENG', name: '英格兰', en: 'England', adj: '英格兰', color: C('#cf4d4d'),
    capital: ['伦敦', -0.13, 51.5], religion: 'catholic', culture: 'english', tech: 'western', gov: 'monarchy', weight: 12, hre: false,
    names: ['米德尔塞克斯','埃塞克斯','肯特','苏塞克斯','威塞克斯','默西亚','诺森布里亚','约克','兰开夏','威尔士','康沃尔','德文','多塞特','格洛斯特','林肯','诺福克','萨福克','牛津','剑桥','沃里克','萨默塞特','威尔特'] },
  { tag: 'BRB', name: '布列塔尼', en: 'Brittany', adj: '布列塔尼', color: C('#4f8f7f'),
    capital: ['雷恩', -1.68, 48.11], religion: 'catholic', culture: 'french', tech: 'western', gov: 'monarchy', weight: 3, hre: false,
    names: ['雷恩','布列塔尼','南特','瓦讷','布雷斯特','莫尔比昂'] },
  { tag: 'SCO', name: '苏格兰', en: 'Scotland', adj: '苏格兰', color: C('#2f5f8f'),
    capital: ['爱丁堡', -3.19, 55.95], religion: 'catholic', culture: 'scottish', tech: 'western', gov: 'monarchy', weight: 5, hre: false,
    names: ['爱丁堡','苏格兰','低地','高地','格拉斯哥','斯特林','珀斯','阿伯丁','法夫','洛锡安','边区'] },
  { tag: 'LEI', name: '伦斯特', en: 'Leinster', adj: '爱尔兰', color: C('#3f7f4f'),
    capital: ['都柏林', -6.27, 53.35], religion: 'catholic', culture: 'irish', tech: 'western', gov: 'monarchy', weight: 1.5, hre: false,
    names: ['伦斯特','都柏林','韦克斯福德','基尔肯尼','卡洛'] },
  { tag: 'MUN', name: '芒斯特', en: 'Munster', adj: '爱尔兰', color: C('#4f8f4f'),
    capital: ['科克', -8.47, 51.9], religion: 'catholic', culture: 'irish', tech: 'western', gov: 'monarchy', weight: 1.5, hre: false,
    names: ['芒斯特','科克','利默里克','凯里','沃特福德'] },
  { tag: 'CON', name: '康诺特', en: 'Connacht', adj: '爱尔兰', color: C('#5f9f4f'),
    capital: ['戈尔韦', -9.05, 53.27], religion: 'catholic', culture: 'irish', tech: 'western', gov: 'monarchy', weight: 1.5, hre: false,
    names: ['康诺特','戈尔韦','斯莱戈','梅奥'] },
  { tag: 'ULS', name: '阿尔斯特', en: 'Ulster', adj: '爱尔兰', color: C('#6faf4f'),
    capital: ['阿马', -6.65, 54.35], religion: 'catholic', culture: 'irish', tech: 'western', gov: 'monarchy', weight: 1.5, hre: false,
    names: ['阿尔斯特','阿马','贝尔法斯特','伦敦德里','安特里姆'] },

  /* ─── 伊比利亚 ─── */
  { tag: 'CAS', name: '卡斯蒂利亚', en: 'Castile', adj: '卡斯蒂利亚', color: C('#d4b43a'),
    capital: ['托莱多', -4.03, 39.86], religion: 'catholic', culture: 'iberian', tech: 'western', gov: 'monarchy', weight: 20, hre: false,
    names: ['托莱多','马德里','卡斯蒂利亚','莱昂','阿斯图里亚斯','加利西亚','埃斯特雷马杜拉','安达卢西亚','穆尔西亚','科尔多瓦','塞维利亚','布尔戈斯','索里亚','瓜达拉哈拉','昆卡','雷阿尔城','巴达霍斯','萨拉曼卡','萨莫拉','帕伦西亚','巴利亚多利德'] },
  { tag: 'ARA', name: '阿拉贡', en: 'Aragon', adj: '阿拉贡', color: C('#a05a2c'),
    capital: ['萨拉戈萨', -0.88, 41.65], religion: 'catholic', culture: 'iberian', tech: 'western', gov: 'monarchy', weight: 10, hre: false,
    capital2: [['巴勒莫', 13.36, 38.12], ['卡利亚里', 9.09, 39.22]],
    names: ['阿拉贡','加泰罗尼亚','巴塞罗那','瓦伦西亚','巴利阿里群岛','撒丁岛','西西里','卡利亚里','巴勒莫','墨西拿','萨拉戈萨','莱里达','赫罗纳','塔拉戈纳','巴伦西亚城','德尼亚','马略卡'] },
  { tag: 'POR', name: '葡萄牙', en: 'Portugal', adj: '葡萄牙', color: C('#2f7d63'),
    capital: ['里斯本', -9.14, 38.72], religion: 'catholic', culture: 'iberian', tech: 'western', gov: 'monarchy', weight: 7, hre: false,
    names: ['里斯本','阿尔加维','阿连特茹','贝拉','波尔图','米尼奥','特拉斯-奥斯-蒙特斯','里巴特茹','上阿连特茹','下阿连特茹'] },
  { tag: 'GRA', name: '格拉纳达', en: 'Granada', adj: '格拉纳达', color: C('#6b4c35'),
    capital: ['格拉纳达', -3.6, 37.18], religion: 'sunni', culture: 'berber', tech: 'muslim', gov: 'monarchy', weight: 3, hre: false,
    names: ['格拉纳达','阿尔梅里亚','马拉加','阿尔普哈拉斯','哈恩'] },

  /* ─── 法兰西东/德意志 ─── */
  { tag: 'BUR', name: '勃艮第', en: 'Burgundy', adj: '勃艮第', color: C('#7a3b6a'),
    capital: ['第戎', 5.04, 47.32], religion: 'catholic', culture: 'french', tech: 'western', gov: 'monarchy', weight: 8, hre: false,
    names: ['勃艮第','第戎','弗朗什-孔泰','佛兰德斯','布拉班特','荷兰','泽兰','埃诺','那慕尔','卢森堡','阿图瓦','里尔','安特卫普','阿姆斯特丹','根特','布鲁日','列日','乌得勒支'] },
  { tag: 'SAV', name: '萨伏依', en: 'Savoy', adj: '萨伏依', color: C('#6f5f9f'),
    capital: ['都灵', 7.69, 45.07], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'monarchy', weight: 3, hre: false,
    names: ['都灵','萨伏依','尼斯','皮埃蒙特','奥斯塔','萨卢佐'] },
  { tag: 'SWI', name: '瑞士', en: 'Switzerland', adj: '瑞士', color: C('#9f3f3f'),
    capital: ['伯尔尼', 7.44, 46.95], religion: 'catholic', culture: 'german', tech: 'western', gov: 'republic', weight: 3, hre: false,
    names: ['伯尔尼','瑞士','苏黎世','巴塞尔','日内瓦','卢塞恩','弗里堡','索洛图恩','沙夫豪森'] },
  { tag: 'PRO', name: '普罗旺斯', en: 'Provence', adj: '普罗旺斯', color: C('#6f7f9f'),
    capital: ['艾克斯', 5.45, 43.53], religion: 'catholic', culture: 'french', tech: 'western', gov: 'monarchy', weight: 2, hre: false,
    names: ['艾克斯','普罗旺斯','马赛','土伦','尼斯','福卡尔基耶'] },
  { tag: 'LOR', name: '洛林', en: 'Lorraine', adj: '洛林', color: C('#7f8f3f'),
    capital: ['南锡', 6.18, 48.69], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 2, hre: true,
    names: ['南锡','洛林','梅斯','凡尔登','图勒'] },

  /* ─── 哈布斯堡/波希米亚 ─── */
  { tag: 'AUT', name: '奥地利', en: 'Austria', adj: '奥地利', color: C('#b03a3a'),
    capital: ['维也纳', 16.37, 48.21], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 8, hre: true, emperor: true,
    names: ['维也纳','施蒂利亚','克恩滕','克雷恩','蒂罗尔','下奥地利','维也纳新城','林茨','格拉茨','克拉根福'] },
  { tag: 'BOH', name: '波希米亚', en: 'Bohemia', adj: '波希米亚', color: C('#5a8f3e'),
    capital: ['布拉格', 14.42, 50.08], religion: 'hussite', culture: 'czech', tech: 'western', gov: 'monarchy', weight: 5, hre: true,
    names: ['布拉格','波希米亚','摩拉维亚','西里西亚','奥洛穆茨','比尔森','库特纳霍拉','利托梅日采','布尔诺'] },
  { tag: 'HUN', name: '匈牙利', en: 'Hungary', adj: '匈牙利', color: C('#3a7a3a'),
    capital: ['布达', 19.04, 47.5], religion: 'catholic', culture: 'hungarian', tech: 'eastern', gov: 'monarchy', weight: 8, hre: false,
    names: ['布达','佩斯','匈牙利','特兰西瓦尼亚','克罗地亚','斯拉沃尼亚','达尔马提亚','埃尔德利','蒂米什瓦拉','科希策','佩奇','塞格德','德布勒森'] },

  /* ─── 意大利 ─── */
  { tag: 'VEN', name: '威尼斯', en: 'Venice', adj: '威尼斯', color: C('#7f3f8f'),
    capital: ['威尼斯', 12.33, 45.44], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'republic', weight: 5, hre: false,
    names: ['威尼斯','维罗纳','帕多瓦','特雷维索','维琴察','乌迪内','伊斯特拉','达尔马提亚','扎拉','科孚','克里特','爱奥尼亚群岛'] },
  { tag: 'GEN', name: '热那亚', en: 'Genoa', adj: '热那亚', color: C('#3f5f8f'),
    capital: ['热那亚', 8.95, 44.41], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'republic', weight: 4, hre: false,
    names: ['热那亚','利古里亚','科西嘉','萨沃纳','尼斯'] },
  { tag: 'MIL', name: '米兰', en: 'Milan', adj: '米兰', color: C('#6b6b6b'),
    capital: ['米兰', 9.19, 45.46], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'monarchy', weight: 4, hre: false,
    names: ['米兰','伦巴第','帕维亚','克雷莫纳','布雷西亚','贝加莫','科莫','洛迪','亚历山德里亚'] },
  { tag: 'FLO', name: '佛罗伦萨', en: 'Florence', adj: '佛罗伦萨', color: C('#9f5f3f'),
    capital: ['佛罗伦萨', 11.25, 43.77], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'republic', weight: 3, hre: false,
    names: ['佛罗伦萨','托斯卡纳','比萨','锡耶纳','卢卡','阿雷佐','皮斯托亚','埃尔萨'] },
  { tag: 'PAP', name: '教皇国', en: 'Papal States', adj: '教皇国', color: C('#cfc06f'),
    capital: ['罗马', 12.5, 41.9], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'theocracy', weight: 3, hre: false,
    names: ['罗马','拉齐奥','安科纳','乌尔比诺','佩鲁贾'] },
  { tag: 'NAP', name: '那不勒斯', en: 'Naples', adj: '那不勒斯', color: C('#4f5faf'),
    capital: ['那不勒斯', 14.27, 40.85], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'monarchy', weight: 7, hre: false,
    names: ['那不勒斯','阿普利亚','卡拉布里亚','坎帕尼亚','阿布鲁佐','莫利塞','巴里','莱切','雷焦'] },
  { tag: 'MOD', name: '摩德纳', en: 'Modena', adj: '摩德纳', color: C('#9f7f3f'),
    capital: ['摩德纳', 10.93, 44.65], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'monarchy', weight: 1, hre: false,
    names: ['摩德纳','摩德纳公国','雷焦艾米利亚'] },
  { tag: 'MAN', name: '曼托瓦', en: 'Mantua', adj: '曼托瓦', color: C('#8f5f8f'),
    capital: ['曼托瓦', 10.79, 45.16], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'monarchy', weight: 1, hre: false,
    names: ['曼托瓦','曼托瓦公国'] },
  { tag: 'FER', name: '费拉拉', en: 'Ferrara', adj: '费拉拉', color: C('#7f7f9f'),
    capital: ['费拉拉', 11.62, 44.84], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'monarchy', weight: 1, hre: false,
    names: ['费拉拉','费拉拉公国'] },
  { tag: 'SIE', name: '锡耶纳', en: 'Siena', adj: '锡耶纳', color: C('#9f8f5f'),
    capital: ['锡耶纳', 11.33, 43.32], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'republic', weight: 1, hre: false,
    names: ['锡耶纳共和国','锡耶纳'] },
  { tag: 'LUC', name: '卢卡', en: 'Lucca', adj: '卢卡', color: C('#6f7f6f'),
    capital: ['卢卡', 10.5, 43.84], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'republic', weight: 1, hre: false,
    names: ['卢卡共和国','卢卡'] },
  { tag: 'MON', name: '蒙费拉托', en: 'Montferrat', adj: '蒙费拉托', color: C('#5f8f8f'),
    capital: ['卡萨莱', 8.45, 45.13], religion: 'catholic', culture: 'italian', tech: 'western', gov: 'monarchy', weight: 1, hre: false,
    names: ['卡萨莱','蒙费拉托'] },
  { tag: 'ATH', name: '雅典', en: 'Athens', adj: '雅典', color: C('#4f6f6f'),
    capital: ['雅典', 23.73, 37.98], religion: 'catholic', culture: 'latin', tech: 'western', gov: 'monarchy', weight: 1, hre: false,
    names: ['雅典','底比斯','优卑亚','雅典公国'] },
  { tag: 'MOE', name: '摩里亚', en: 'Morea', adj: '摩里亚', color: C('#5f5f9f'),
    capital: ['米斯特拉斯', 22.14, 37.07], religion: 'orthodox', culture: 'greek', tech: 'eastern', gov: 'monarchy', weight: 1.5, hre: false,
    names: ['米斯特拉斯','摩里亚','莫奈姆瓦西亚','斯巴达'] },

  /* ─── 德意志诸侯 ─── */
  { tag: 'BAV', name: '巴伐利亚', en: 'Bavaria', adj: '巴伐利亚', color: C('#3f6f9f'),
    capital: ['慕尼黑', 11.58, 48.14], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 3, hre: true,
    names: ['慕尼黑','巴伐利亚','施瓦本','雷根斯堡','奥格斯堡','兰茨胡特','因戈尔施塔特','施特劳宾'] },
  { tag: 'SAX', name: '萨克森', en: 'Saxony', adj: '萨克森', color: C('#5f7f4f'),
    capital: ['德累斯顿', 13.74, 51.05], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 3, hre: true,
    names: ['德累斯顿','萨克森','迈森','莱比锡','图林根','维滕贝格'] },
  { tag: 'BRA', name: '勃兰登堡', en: 'Brandenburg', adj: '勃兰登堡', color: C('#4f4f8f'),
    capital: ['柏林', 13.4, 52.52], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 3, hre: true,
    names: ['柏林','勃兰登堡','勃兰登堡边疆','诺伊马克'] },
  { tag: 'PAL', name: '普法尔茨', en: 'The Palatinate', adj: '普法尔茨', color: C('#7f5f9f'),
    capital: ['海德堡', 8.69, 49.41], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 2, hre: true,
    names: ['海德堡','普法尔茨','曼海姆','茨韦布吕肯','下普法尔茨'] },
  { tag: 'COL', name: '科隆', en: 'Cologne', adj: '科隆', color: C('#8f3f3f'),
    capital: ['科隆', 6.96, 50.94], religion: 'catholic', culture: 'german', tech: 'western', gov: 'theocracy', weight: 2, hre: true,
    names: ['科隆','科隆选侯国','亚琛','波恩','于利希'] },
  { tag: 'MAI', name: '美因茨', en: 'Mainz', adj: '美因茨', color: C('#8f6f3f'),
    capital: ['美因茨', 8.27, 50.0], religion: 'catholic', culture: 'german', tech: 'western', gov: 'theocracy', weight: 2, hre: true,
    names: ['美因茨','美因茨选侯国','威斯巴登','阿尔蔡'] },
  { tag: 'WUR', name: '符腾堡', en: 'Württemberg', adj: '符腾堡', color: C('#6f9f6f'),
    capital: ['斯图加特', 9.18, 48.78], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 1, hre: true,
    names: ['斯图加特','符腾堡','蒂宾根','海尔布隆'] },
  { tag: 'HES', name: '黑森', en: 'Hesse', adj: '黑森', color: C('#7f7f5f'),
    capital: ['卡塞尔', 9.5, 51.31], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 2, hre: true,
    names: ['卡塞尔','黑森','马尔堡','吉森','富尔达'] },
  { tag: 'BRU', name: '不伦瑞克', en: 'Brunswick', adj: '不伦瑞克', color: C('#5f5f7f'),
    capital: ['不伦瑞克', 10.53, 52.27], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 2, hre: true,
    names: ['不伦瑞克','布伦瑞克-沃尔芬比特尔','哥廷根'] },
  { tag: 'MEC', name: '梅克伦堡', en: 'Mecklenburg', adj: '梅克伦堡', color: C('#4f7f7f'),
    capital: ['什未林', 11.4, 53.63], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 1, hre: true,
    names: ['什未林','梅克伦堡','罗斯托克','维斯马'] },
  { tag: 'POM', name: '波美拉尼亚', en: 'Pomerania', adj: '波美拉尼亚', color: C('#6f8f4f'),
    capital: ['斯德丁', 14.55, 53.43], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 2, hre: true,
    names: ['斯德丁','波美拉尼亚','施特拉尔松德','科沃布热格'] },
  { tag: 'FRI', name: '东弗里斯兰', en: 'East Frisia', adj: '弗里斯兰', color: C('#8f8f4f'),
    capital: ['埃姆登', 7.2, 53.37], religion: 'catholic', culture: 'german', tech: 'western', gov: 'monarchy', weight: 1, hre: true,
    names: ['埃姆登','东弗里斯兰','格罗宁根','弗里斯兰'] },
  { tag: 'UTR', name: '乌得勒支', en: 'Utrecht', adj: '乌得勒支', color: C('#7f4f7f'),
    capital: ['乌得勒支', 5.12, 52.09], religion: 'catholic', culture: 'german', tech: 'western', gov: 'theocracy', weight: 1, hre: true,
    names: ['乌得勒支'] },
  { tag: 'LIE', name: '列日', en: 'Liège', adj: '列日', color: C('#8f6f6f'),
    capital: ['列日', 5.57, 50.63], religion: 'catholic', culture: 'german', tech: 'western', gov: 'theocracy', weight: 1, hre: true,
    names: ['列日','列日采邑主教区','于伊'] },

  /* ─── 北欧 ─── */
  { tag: 'DEN', name: '丹麦', en: 'Denmark', adj: '丹麦', color: C('#a03a5a'),
    capital: ['哥本哈根', 12.57, 55.68], religion: 'catholic', culture: 'scandinavian', tech: 'western', gov: 'monarchy', weight: 4, hre: false,
    names: ['哥本哈根','西兰','日德兰','菲英','斯堪尼亚','哈兰','布莱金厄','博恩霍尔姆'] },
  { tag: 'SWE', name: '瑞典', en: 'Sweden', adj: '瑞典', color: C('#3f6f9f'),
    capital: ['斯德哥尔摩', 18.07, 59.33], religion: 'catholic', culture: 'scandinavian', tech: 'western', gov: 'monarchy', weight: 7, hre: false,
    names: ['斯德哥尔摩','乌普兰','斯韦阿兰','西约特兰','东约特兰','达拉纳','耶姆特兰','韦姆兰','耶斯特里克兰','海耶达尔','芬兰','埃博','塔瓦斯提拉'] },
  { tag: 'NOR', name: '挪威', en: 'Norway', adj: '挪威', color: C('#5a6b8f'),
    capital: ['奥斯陆', 10.75, 59.91], religion: 'catholic', culture: 'scandinavian', tech: 'western', gov: 'monarchy', weight: 6, hre: false,
    names: ['奥斯陆','挪威','维肯','西福尔','默勒-鲁姆斯达尔','特伦德拉格','诺尔兰','特罗姆斯','芬马克','卑尔根','斯塔万格','阿格德尔'] },

  /* ─── 波兰/波罗的海 ─── */
  { tag: 'POL', name: '波兰', en: 'Poland', adj: '波兰', color: C('#8c2f3f'),
    capital: ['克拉科夫', 19.94, 50.06], religion: 'catholic', culture: 'polish', tech: 'eastern', gov: 'monarchy', weight: 10, hre: false,
    names: ['克拉科夫','波兰','马佐维亚','小波兰','大波兰','桑多梅日','谢拉兹','桑比亚','库亚维','沃里尼亚','波多利亚','卢布林','普沃茨克','切尔斯克'] },
  { tag: 'LIT', name: '立陶宛', en: 'Lithuania', adj: '立陶宛', color: C('#3f6b8c'),
    capital: ['维尔纽斯', 25.28, 54.69], religion: 'catholic', culture: 'lithuanian', tech: 'eastern', gov: 'monarchy', weight: 9, hre: false,
    names: ['维尔纽斯','立陶宛','萨莫吉希亚','特拉凯','波洛茨克','明斯克','格罗德诺','布雷斯特','沃尔希尼亚','波德拉谢'] },
  { tag: 'TEU', name: '条顿骑士团', en: 'Teutonic Order', adj: '条顿', color: C('#cfcfcf'),
    capital: ['柯尼斯堡', 20.45, 54.71], religion: 'catholic', culture: 'german', tech: 'western', gov: 'theocracy', weight: 4, hre: false,
    names: ['柯尼斯堡','条顿骑士团','普鲁士','但泽','库尔兰','埃尔宾','马林堡'] },
  { tag: 'LIV', name: '利沃尼亚骑士团', en: 'Livonian Order', adj: '利沃尼亚', color: C('#9f9f7f'),
    capital: ['里加', 24.1, 56.95], religion: 'catholic', culture: 'german', tech: 'western', gov: 'theocracy', weight: 3, hre: false,
    names: ['里加','利沃尼亚骑士团','爱沙尼亚','雷瓦尔','派尔努'] },

  /* ─── 罗斯 ─── */
  { tag: 'MOS', name: '莫斯科', en: 'Muscovy', adj: '莫斯科', color: C('#8f8f3f'),
    capital: ['莫斯科', 37.62, 55.75], religion: 'orthodox', culture: 'russian', tech: 'eastern', gov: 'monarchy', weight: 16, hre: false,
    names: ['莫斯科','莫斯科大公国','弗拉基米尔','苏兹达尔','雅罗斯拉夫尔','特维尔','梁赞','罗斯托夫','下诺夫哥罗德','莫扎伊斯克','科斯特罗马','加利奇','佩列亚斯拉夫尔','乌格利奇','德米特罗夫'] },
  { tag: 'NOV', name: '诺夫哥罗德', en: 'Novgorod', adj: '诺夫哥罗德', color: C('#4f7f7f'),
    capital: ['诺夫哥罗德', 31.28, 58.53], religion: 'orthodox', culture: 'russian', tech: 'eastern', gov: 'republic', weight: 6, hre: false,
    names: ['诺夫哥罗德','普斯科夫','沃洛格达','奥涅加','白海','科雷拉','乌斯秋格','托尔若克','拉多加'] },
  { tag: 'RYA', name: '梁赞', en: 'Ryazan', adj: '梁赞', color: C('#7f7f9f'),
    capital: ['梁赞', 39.7, 54.63], religion: 'orthodox', culture: 'russian', tech: 'eastern', gov: 'monarchy', weight: 2, hre: false,
    names: ['梁赞','穆罗姆','科洛姆纳','普龙斯克'] },
  { tag: 'TVE', name: '特维尔', en: 'Tver', adj: '特维尔', color: C('#5f7f5f'),
    capital: ['特维尔', 35.9, 56.86], religion: 'orthodox', culture: 'russian', tech: 'eastern', gov: 'monarchy', weight: 2, hre: false,
    names: ['特维尔','托尔若克','别热茨基','卡申'] },
  { tag: 'PSK', name: '普斯科夫', en: 'Pskov', adj: '普斯科夫', color: C('#5f5f7f'),
    capital: ['普斯科夫', 28.33, 57.82], religion: 'orthodox', culture: 'russian', tech: 'eastern', gov: 'republic', weight: 1, hre: false,
    names: ['普斯科夫','伊兹博斯克','格多夫'] },

  /* ─── 草原/游牧 ─── */
  { tag: 'GOL', name: '金帐汗国', en: 'Great Horde', adj: '金帐', color: C('#8f6f4f'),
    capital: ['萨莱', 47.9, 48.6], religion: 'sunni', culture: 'turkish', tech: 'nomad', gov: 'horde', weight: 8, hre: false,
    names: ['萨莱','金帐汗国','阿斯特拉罕','萨拉托夫','伏尔加','萨马拉','乌法','奥伦堡'] },
  { tag: 'CRI', name: '克里米亚', en: 'Crimea', adj: '克里米亚', color: C('#6f8f6f'),
    capital: ['巴赫奇萨赖', 33.9, 44.75], religion: 'sunni', culture: 'turkish', tech: 'nomad', gov: 'horde', weight: 2, hre: false,
    names: ['巴赫奇萨赖','克里米亚','卡法','刻赤','费奥多西亚'] },
  { tag: 'KAZ', name: '喀山', en: 'Kazan', adj: '喀山', color: C('#7f7f4f'),
    capital: ['喀山', 49.1, 55.79], religion: 'sunni', culture: 'turkish', tech: 'nomad', gov: 'horde', weight: 3, hre: false,
    names: ['喀山','鞑靼斯坦','阿拉特里','切博克萨雷'] },
  { tag: 'AST', name: '阿斯特拉罕', en: 'Astrakhan', adj: '阿斯特拉罕', color: C('#8f5f5f'),
    capital: ['阿斯特拉罕', 48.0, 46.35], religion: 'sunni', culture: 'turkish', tech: 'nomad', gov: 'horde', weight: 2, hre: false,
    names: ['阿斯特拉罕','萨赖朱克','下伏尔加'] },

  /* ─── 巴尔干 ─── */
  { tag: 'SER', name: '塞尔维亚', en: 'Serbia', adj: '塞尔维亚', color: C('#4f7f4f'),
    capital: ['斯梅代雷沃', 20.93, 44.66], religion: 'orthodox', culture: 'serbian', tech: 'eastern', gov: 'monarchy', weight: 4, hre: false,
    names: ['斯梅代雷沃','塞尔维亚','贝尔格莱德','拉什卡','科索沃','尼什','兹拉蒂博尔'] },
  { tag: 'BOS', name: '波斯尼亚', en: 'Bosnia', adj: '波斯尼亚', color: C('#6f6f8f'),
    capital: ['萨拉热窝', 18.41, 43.86], religion: 'catholic', culture: 'croatian', tech: 'eastern', gov: 'monarchy', weight: 2, hre: false,
    names: ['萨拉热窝','波斯尼亚','乌纳','弗尔巴斯','德里纳'] },
  { tag: 'ALB', name: '阿尔巴尼亚', en: 'Albania', adj: '阿尔巴尼亚', color: C('#7f4f4f'),
    capital: ['克鲁亚', 19.79, 41.5], religion: 'orthodox', culture: 'serbian', tech: 'eastern', gov: 'monarchy', weight: 1, hre: false,
    names: ['克鲁亚','阿尔巴尼亚','都拉斯','发罗拉','斯库台'] },
  { tag: 'RAG', name: '拉古萨', en: 'Ragusa', adj: '拉古萨', color: C('#3f7f8f'),
    capital: ['杜布罗夫尼克', 18.1, 42.65], religion: 'catholic', culture: 'croatian', tech: 'western', gov: 'republic', weight: 1, hre: false,
    names: ['拉古萨','杜布罗夫尼克'] },
  { tag: 'WAL', name: '瓦拉几亚', en: 'Wallachia', adj: '瓦拉几亚', color: C('#8f4f6f'),
    capital: ['特尔戈维什泰', 25.46, 45.03], religion: 'orthodox', culture: 'romanian', tech: 'eastern', gov: 'monarchy', weight: 3, hre: false,
    names: ['特尔戈维什泰','瓦拉几亚','蒙特尼亚','奥尔特尼亚'] },
  { tag: 'MOL', name: '摩尔达维亚', en: 'Moldavia', adj: '摩尔达维亚', color: C('#4f6f8f'),
    capital: ['苏恰瓦', 26.25, 47.65], religion: 'orthodox', culture: 'romanian', tech: 'eastern', gov: 'monarchy', weight: 3, hre: false,
    names: ['苏恰瓦','摩尔达维亚','巴克乌','雅西','比萨拉比亚'] },

  /* ─── 奥斯曼/拜占庭 ─── */
  { tag: 'OTT', name: '奥斯曼', en: 'Ottomans', adj: '奥斯曼', color: C('#2f7f5f'),
    capital: ['埃迪尔内', 26.56, 41.68], religion: 'sunni', culture: 'turkish', tech: 'ottoman', gov: 'monarchy', weight: 16, hre: false,
    names: ['埃迪尔内','色雷斯','安纳托利亚','鲁米利亚','卡拉曼','卡斯塔莫努','安卡拉','布尔萨','士麦那','阿德里安堡','加济安泰普','迪亚巴克尔','锡瓦斯','特拉布宗','萨姆松','科尼亚','伊兹密尔'] },
  { tag: 'BYZ', name: '拜占庭', en: 'Byzantium', adj: '拜占庭', color: C('#7f2f4f'),
    capital: ['君士坦丁堡', 28.98, 41.01], religion: 'orthodox', culture: 'greek', tech: 'eastern', gov: 'monarchy', weight: 2, hre: false,
    names: ['君士坦丁堡','摩里亚','比提尼亚','尼西亚','科林斯','帕特雷','米斯特拉斯'] },

  /* ─── 穆斯林世界 ─── */
  { tag: 'MAM', name: '马穆鲁克', en: 'Mamluks', adj: '马穆鲁克', color: C('#8f7f3f'),
    capital: ['开罗', 31.25, 30.05], religion: 'sunni', culture: 'arabic', tech: 'muslim', gov: 'monarchy', weight: 8, hre: false,
    names: ['开罗','埃及','尼罗河三角洲','亚历山大','西奈','法尤姆','上埃及','古斯','达米埃塔','拉希德','比勒拜斯'] },
  { tag: 'MOR', name: '摩洛哥', en: 'Morocco', adj: '摩洛哥', color: C('#7f5f2f'),
    capital: ['非斯', -5.0, 34.03], religion: 'sunni', culture: 'berber', tech: 'muslim', gov: 'monarchy', weight: 6, hre: false,
    names: ['非斯','摩洛哥','马拉喀什','丹吉尔','梅克内斯','拉巴特','苏斯','德拉'] },
  { tag: 'TUN', name: '突尼斯', en: 'Tunis', adj: '突尼斯', color: C('#3f8f7f'),
    capital: ['突尼斯城', 10.18, 36.8], religion: 'sunni', culture: 'berber', tech: 'muslim', gov: 'monarchy', weight: 5, hre: false,
    names: ['突尼斯城','突尼斯','凯鲁万','斯法克斯','加贝斯','比塞大','马赫迪耶'] },
  { tag: 'ALG', name: '特莱姆森', en: 'Tlemcen', adj: '特莱姆森', color: C('#6f8f4f'),
    capital: ['特莱姆森', -1.31, 34.88], religion: 'sunni', culture: 'berber', tech: 'muslim', gov: 'monarchy', weight: 3, hre: false,
    names: ['特莱姆森','阿尔及尔','奥兰','君士坦丁','安纳巴','布吉'] },
  { tag: 'AQD', name: '白羊王朝', en: 'Aq Qoyunlu', adj: '白羊', color: C('#4f8f8f'),
    capital: ['迪亚巴克尔', 40.24, 37.91], religion: 'sunni', culture: 'azeri', tech: 'muslim', gov: 'monarchy', weight: 5, hre: false,
    names: ['迪亚巴克尔','白羊王朝','凡城','比特利斯','埃尔祖鲁姆','马拉蒂亚','加济安泰普'] },
  { tag: 'QQY', name: '黑羊王朝', en: 'Qara Qoyunlu', adj: '黑羊', color: C('#3f7f6f'),
    capital: ['大不里士', 46.29, 38.08], religion: 'shia', culture: 'azeri', tech: 'muslim', gov: 'monarchy', weight: 4, hre: false,
    names: ['大不里士','黑羊王朝','阿塞拜疆','阿尔达比勒','马哈巴德'] },
  { tag: 'SHI', name: '希尔凡', en: 'Shirvan', adj: '希尔凡', color: C('#5f8f5f'),
    capital: ['沙马基', 48.64, 40.63], religion: 'sunni', culture: 'azeri', tech: 'muslim', gov: 'monarchy', weight: 1, hre: false,
    names: ['沙马基','希尔凡','巴库'] },
  { tag: 'GEO', name: '格鲁吉亚', en: 'Georgia', adj: '格鲁吉亚', color: C('#6f4f8f'),
    capital: ['第比利斯', 44.83, 41.72], religion: 'orthodox', culture: 'georgian', tech: 'eastern', gov: 'monarchy', weight: 2, hre: false,
    names: ['第比利斯','格鲁吉亚','伊梅列季','卡尔特利','卡赫季'] },
  { tag: 'CYP', name: '塞浦路斯', en: 'Cyprus', adj: '塞浦路斯', color: C('#8f8f5f'),
    capital: ['尼科西亚', 33.37, 35.17], religion: 'catholic', culture: 'greek', tech: 'western', gov: 'monarchy', weight: 1, hre: false,
    names: ['尼科西亚','法马古斯塔','利马索尔'] },
  { tag: 'KNI', name: '医院骑士团', en: 'Knights Hospitaller', adj: '医院骑士团', color: C('#af2f2f'),
    capital: ['罗得岛', 28.22, 36.44], religion: 'catholic', culture: 'latin', tech: 'western', gov: 'theocracy', weight: 1, hre: false,
    names: ['罗得岛'] },
];

/* 文化/宗教 缺省提示：方便世界生成时填充未拥有地区 */
export const DEFAULTS_BY_TERRAIN = {
  farmland: { devBase: 6, goods: ['grain', 'wine', 'wool', 'cloth'] },
  forest: { devBase: 4, goods: ['lumber', 'fur', 'grain'] },
  hills: { devBase: 4, goods: ['iron', 'salt', 'wine', 'copper'] },
  alpine: { devBase: 3, goods: ['iron', 'gold', 'salt', 'copper'] },
  coastal: { devBase: 5, goods: ['fish', 'salt', 'wine'] },
  steppe: { devBase: 3, goods: ['wool', 'horses', 'grain'] },
  desert: { devBase: 2, goods: ['cotton', 'spices', 'salt'] },
  ocean: { devBase: 1, goods: ['fish'] },
  tundra: { devBase: 2, goods: ['fur', 'fish'] },
};

export const TRADE_GOODS = {
  grain: '谷物', wine: '葡萄酒', wool: '羊毛', cloth: '布匹', fish: '鱼类',
  salt: '盐', iron: '铁', gold: '黄金', copper: '铜', lumber: '木材', fur: '毛皮',
  horses: '马匹', cotton: '棉花', spices: '香料', silk: '丝绸',
};

export const TERRAINS = {
  farmland: { name: '农田', en: 'Farmland', color: [202, 214, 148] },
  forest: { name: '森林', en: 'Forest', color: [100, 142, 90] },
  hills: { name: '丘陵', en: 'Hills', color: [194, 178, 118] },
  alpine: { name: '山地', en: 'Mountains', color: [168, 160, 152] },
  coastal: { name: '海岸', en: 'Coast', color: [222, 210, 164] },
  steppe: { name: '草原', en: 'Steppe', color: [212, 198, 132] },
  desert: { name: '沙漠', en: 'Desert', color: [230, 210, 166] },
  ocean: { name: '海洋', en: 'Ocean', color: [138, 174, 184] },
  tundra: { name: '苔原', en: 'Tundra', color: [196, 204, 196] },
};
