export const MAP = {
  HALF_SIZE: 60,
};

export const PLAYER = {
  EYE_HEIGHT: 1.7,
  MOVE_SPEED: 6,
  LOOK_SENSITIVITY: 0.0022,
  RADIUS: 0.4,
  MAX_HEALTH: 100,
};

export const BALANCE = {
  MAX_ALIVE_ENEMIES: 120,
  MAX_WEAPONS: 4,
  SPAWN_START_INTERVAL: 1.1,
  SPAWN_MIN_INTERVAL: 0.18,
  SPAWN_INTERVAL_DECAY: 0.01,
  SPAWN_BATCH_MAX: 4,
  SPAWN_DIST_MIN: 26,
  SPAWN_DIST_MAX: 36,
  HP_SCALE_PER_MIN: 0.25,
  IFRAMES: 0.8,
  CONTACT_DAMAGE_INTERVAL: 0.8,
  GEM_CAPACITY: 160,
  GEM_MAGNET_RADIUS: 5,
  GEM_PICKUP_RADIUS: 0.7,
  PROJECTILE_CAPACITY: 200,
  ENEMY_DIE_TIME: 0.25,
};
