/* ============================================================
 * 《妖怪夜市》script.js —— 剧本
 * 以声明式事件序列描述整场演出，由 main.js（导演）逐条执行
 *
 * 事件类型：
 *   bgm / sfx / bg / fade / wait / title
 *   add / enter / move / exit / emote / remove
 *   say（需观众点击推进） / auto（自动停顿）
 *   flies / embers / bellRing / end
 * ============================================================ */

window.SCRIPT = [

  /* ============ 序幕 · 迷路的孩子 ============ */
  { t: "title", text: "序 幕", sub: "迷路的孩子" },
  { t: "bg", scene: "hill" },
  { t: "bgm", name: "prologue" },
  { t: "flies" },
  { t: "fade", to: 0, dur: 1.6 },
  { t: "wait", ms: 600 },
  { t: "say", who: "旁白", text: "山里的夜，比城里的夜要黑得多。\n七岁的小满追着萤火虫跑远了，一回头，来时的路已经不见了。" },
  { t: "enter", a: "child", from: "left", x: 200, speed: 34 },
  { t: "sfx", name: "step" },
  { t: "emote", a: "child", g: "?" },
  { t: "say", who: "小满", text: "奇怪……这条路，我明明走过一遍的呀。" },
  { t: "move", a: "child", x: 240, speed: 26 },
  { t: "say", who: "小满", text: "咦？前面有一座好大的鸟居。\n门上挂着两盏灯，像是专门给我留的。" },
  { t: "sfx", name: "whoosh" },
  { t: "say", who: "旁白", text: "风里飘来炸天妇罗的香气，还有叮叮当当的铃鼓声。\n鸟居背后，是一片不该存在的灯火。" },
  { t: "emote", a: "child", g: "!" },
  { t: "say", who: "小满", text: "好香……我就看一眼，只看一眼就回家。" },
  { t: "move", a: "child", x: 300, speed: 40 },
  { t: "fade", to: 1, dur: 1.2 },

  /* ============ 第一幕 · 误入 ============ */
  { t: "title", text: "第一幕", sub: "误入夜市" },
  { t: "bg", scene: "gate" },
  { t: "fade", to: 0, dur: 1.2 },
  { t: "move", a: "child", x: 240, speed: 40 },
  { t: "sfx", name: "sparkle" },
  { t: "say", who: "旁白", text: "穿过鸟居的一瞬间，小满的影子变短了。\n耳边响起一声悠长的钟鸣——" },
  { t: "bellRing", x: 240, y: 60 },
  { t: "sfx", name: "bell" },
  { t: "wait", ms: 900 },
  { t: "bg", scene: "street" },
  { t: "bgm", name: "market" },
  { t: "embers" },
  { t: "sfx", name: "whoosh" },
  { t: "say", who: "小满", text: "哇——！\n整条街都是灯笼，摊位从街头排到街尾！" },
  { t: "say", who: "旁白", text: "卖面具的、卖星星糖的、卖「昨夜的梦」的。\n客人们都穿着宽大的袍子——只是影子形状不太对劲。" },
  { t: "enter", a: "fox", from: "right", x: 320, speed: 52 },
  { t: "sfx", name: "pop" },
  { t: "emote", a: "fox", g: "?" },
  { t: "say", who: "???", text: "嗅嗅……这个味道。\n雨水的味道、铅笔的味道，还有——人类小孩的味道。" },
  { t: "emote", a: "child", g: "!" },
  { t: "say", who: "小满", text: "会、会说话的狐狸！" },
  { t: "move", a: "fox", x: 286, speed: 30 },
  { t: "say", who: "阿昆", text: "我叫阿昆，是这条街的向导。\n听好了，小家伙：天亮之前必须离开，不然你就会变成货架上的商品。" },
  { t: "say", who: "小满", text: "变成商品？！" },
  { t: "say", who: "阿昆", text: "上一回留下来的人类，现在还是第 44 号摊位上的招财猫呢。\n……看在你口袋里有半块饼干的份上，我带你逛逛。走吧！" },
  { t: "emote", a: "child", g: "♪" },
  { t: "fade", to: 1, dur: 1.0 },

  /* ============ 第二幕 · 夜市漫游 ============ */
  { t: "title", text: "第二幕", sub: "灯笼与面具" },
  { t: "bg", scene: "street" },
  { t: "fade", to: 0, dur: 1.0 },
  { t: "move", a: "child", x: 150, speed: 46 },
  { t: "move", a: "fox", x: 210, speed: 46 },
  { t: "enter", a: "lantern", from: "right", x: 330, speed: 30 },
  { t: "sfx", name: "pop" },
  { t: "say", who: "灯笼小僧", text: "哎呀呀，今晚来了位稀客！\n要不要一盏「不会熄灭的灯」？只要一首歌来换。" },
  { t: "say", who: "小满", text: "我会唱《一闪一闪亮晶晶》！" },
  { t: "emote", a: "child", g: "♪" },
  { t: "emote", a: "lantern", g: "♪" },
  { t: "sfx", name: "sparkle" },
  { t: "say", who: "灯笼小僧", text: "唱得真好，火光都跟着你跳舞。\n拿着吧，它认得回家的路。" },
  { t: "say", who: "阿昆", text: "别磨蹭啦，面具摊要收摊了！" },
  { t: "exit", a: "lantern", to: "right", speed: 34 },
  { t: "move", a: "child", x: 300, speed: 42 },
  { t: "move", a: "fox", x: 350, speed: 42 },
  { t: "enter", a: "oni", from: "right", x: 420, speed: 26 },
  { t: "say", who: "青鬼摊主", text: "哼哼，小娃娃挑个面具吧。\n戴上它，妖怪就不会发现你是人类。" },
  { t: "say", who: "小满", text: "这个狐狸面具……和阿昆好像。我要这个！" },
  { t: "emote", a: "fox", g: "♥" },
  { t: "say", who: "阿昆", text: "咳、咳！眼光不错。\n……喂，别笑，尾巴都竖起来了的是你吧。" },
  { t: "enter", a: "umbrella", from: "left", x: 120, speed: 24 },
  { t: "say", who: "伞妖", text: "让一让，让一让——\n收摊喽，月亮都打哈欠喽。" },
  { t: "say", who: "旁白", text: "夜市的笑声一层叠着一层。\n小满几乎忘了，自己本是要回家的。" },
  { t: "fade", to: 1, dur: 1.0 },

  /* ============ 第三幕 · 破晓之钟 ============ */
  { t: "title", text: "第三幕", sub: "破晓之钟" },
  { t: "bg", scene: "street" },
  { t: "bgm", name: "tender" },
  { t: "fade", to: 0, dur: 1.0 },
  { t: "move", a: "child", x: 210, speed: 34 },
  { t: "move", a: "fox", x: 268, speed: 34 },
  { t: "say", who: "小满", text: "阿昆，你的围巾真好看。是哪来的？" },
  { t: "say", who: "阿昆", text: "很久以前，有个迷路的女孩把它送给了我。\n她说：「戴着它，黑夜就不冷了。」\n……后来天亮了，她就走了。" },
  { t: "say", who: "小满", text: "你会想她吗？" },
  { t: "say", who: "阿昆", text: "妖怪的时间很长，想念也很长。\n不过没关系——夜市每年都开，故事也每年都有新的。" },
  { t: "bellRing", x: 240, y: 60 },
  { t: "sfx", name: "bell" },
  { t: "wait", ms: 700 },
  { t: "emote", a: "fox", g: "!" },
  { t: "say", who: "阿昆", text: "破晓钟！小满，快跑！\n从鸟居出去，一直跑，别回头！" },
  { t: "exit", a: "umbrella", to: "left", speed: 60 },
  { t: "exit", a: "oni", to: "right", speed: 60 },
  { t: "sfx", name: "whoosh" },
  { t: "say", who: "旁白", text: "灯笼一盏接一盏地暗下去，像退潮的星光。\n小满抱着狐狸面具，朝着鸟居拼命地跑。" },
  { t: "move", a: "child", x: 400, speed: 74 },
  { t: "move", a: "fox", x: 352, speed: 66 },
  { t: "say", who: "小满", text: "阿昆，明年……夜市还会开吗？" },
  { t: "say", who: "阿昆", text: "会的。只要有人在山里迷了路，又闻到了天妇罗的香气。\n围巾借你挡挡风——快走吧，小家伙。" },
  { t: "emote", a: "child", g: "♥" },
  { t: "sfx", name: "sparkle" },
  { t: "fade", to: 1, dur: 1.6 },

  /* ============ 尾声 · 天亮了 ============ */
  { t: "title", text: "尾 声", sub: "天亮了" },
  { t: "bg", scene: "dawn" },
  { t: "bgm", name: "dawn" },
  { t: "remove", a: "fox" },
  { t: "fade", to: 0, dur: 1.8 },
  { t: "sfx", name: "cock" },
  { t: "enter", a: "child", from: "left", x: 220, speed: 30 },
  { t: "say", who: "旁白", text: "晨光漫过山脊的时候，小满站在了家门口的田埂上。\n身后的鸟居，只剩两根长满青苔的旧石柱。" },
  { t: "emote", a: "child", g: "…" },
  { t: "say", who: "小满", text: "是梦吗……？" },
  { t: "wait", ms: 500 },
  { t: "sfx", name: "pop" },
  { t: "say", who: "旁白", text: "怀里抱着狐狸面具，脖子上围着一条红围巾。\n围巾上还留着夜市的温度。" },
  { t: "emote", a: "child", g: "♥" },
  { t: "say", who: "小满", text: "明年，我还要迷路一次。" },
  { t: "fade", to: 1, dur: 2.2 },

  /* ============ 谢幕 ============ */
  { t: "title", text: "谢 幕", sub: "感谢观看 · 妖怪夜市" },
  { t: "stopBgm" },
  { t: "wait", ms: 2600 },
  { t: "end" },
];
